; ModuleID = 'wyn_program'
source_filename = "wyn_program"

@__wyn_argc = global i32 0
@__wyn_argv = global ptr null
@str = private unnamed_addr constant [76 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_01_variables.out\00", align 1
@str.1 = private unnamed_addr constant [76 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_02_functions.out\00", align 1
@str.2 = private unnamed_addr constant [74 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_03_structs.out\00", align 1
@str.3 = private unnamed_addr constant [72 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_04_enums.out\00", align 1
@str.4 = private unnamed_addr constant [73 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_05_arrays.out\00", align 1
@str.5 = private unnamed_addr constant [80 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_06_result_option.out\00", align 1
@str.6 = private unnamed_addr constant [83 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_07_pattern_matching.out\00", align 1
@str.7 = private unnamed_addr constant [79 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_08_control_flow.out\00", align 1
@str.8 = private unnamed_addr constant [79 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_09_type_aliases.out\00", align 1
@str.9 = private unnamed_addr constant [75 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_10_generics.out\00", align 1
@str.10 = private unnamed_addr constant [84 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_11_extension_methods.out\00", align 1
@str.11 = private unnamed_addr constant [78 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_12_concurrency.out\00", align 1
@str.12 = private unnamed_addr constant [79 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_all_12_features.out\00", align 1
@str.13 = private unnamed_addr constant [76 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_all_features.out\00", align 1
@str.14 = private unnamed_addr constant [74 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_all_stdlib.out\00", align 1
@str.15 = private unnamed_addr constant [72 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_arc_heap.out\00", align 1
@str.16 = private unnamed_addr constant [84 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_arc_multiple_structs.out\00", align 1
@str.17 = private unnamed_addr constant [71 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_arc_tdd.out\00", align 1
@str.18 = private unnamed_addr constant [67 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_arc.out\00", align 1
@str.19 = private unnamed_addr constant [77 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_array_methods.out\00", align 1
@str.20 = private unnamed_addr constant [77 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_array_various.out\00", align 1
@str.21 = private unnamed_addr constant [76 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_arrays_final.out\00", align 1
@str.22 = private unnamed_addr constant [70 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_arrays.out\00", align 1
@str.23 = private unnamed_addr constant [83 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_async_comprehensive.out\00", align 1
@str.24 = private unnamed_addr constant [78 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_async_multiple.out\00", align 1
@str.25 = private unnamed_addr constant [73 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_async_tdd.out\00", align 1
@str.26 = private unnamed_addr constant [69 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_async.out\00", align 1
@str.27 = private unnamed_addr constant [69 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_basic.out\00", align 1
@str.28 = private unnamed_addr constant [68 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_bool.out\00", align 1
@str.29 = private unnamed_addr constant [72 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_booleans.out\00", align 1
@str.30 = private unnamed_addr constant [69 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_break.out\00", align 1
@str.31 = private unnamed_addr constant [76 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_build_system.out\00", align 1
@str.32 = private unnamed_addr constant [77 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_closure_basic.out\00", align 1
@str.33 = private unnamed_addr constant [81 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_closure_nocapture.out\00", align 1
@str.34 = private unnamed_addr constant [78 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_closure_simple.out\00", align 1
@str.35 = private unnamed_addr constant [82 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_collection_methods.out\00", align 1
@str.36 = private unnamed_addr constant [74 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_comparison.out\00", align 1
@str.37 = private unnamed_addr constant [85 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_comprehensive_methods.out\00", align 1
@str.38 = private unnamed_addr constant [77 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_comprehensive.out\00", align 1
@str.39 = private unnamed_addr constant [80 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_concurrency_real.out\00", align 1
@str.40 = private unnamed_addr constant [72 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_continue.out\00", align 1
@str.41 = private unnamed_addr constant [75 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_edge_concat.out\00", align 1
@str.42 = private unnamed_addr constant [82 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_edge_empty_strings.out\00", align 1
@str.43 = private unnamed_addr constant [83 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_edge_multiple_calls.out\00", align 1
@str.44 = private unnamed_addr constant [76 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_edge_numbers.out\00", align 1
@str.45 = private unnamed_addr constant [77 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_edge_repeated.out\00", align 1
@str.46 = private unnamed_addr constant [82 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_edge_special_chars.out\00", align 1
@str.47 = private unnamed_addr constant [78 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_edge_substring.out\00", align 1
@str.48 = private unnamed_addr constant [75 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_edge_typeof.out\00", align 1
@str.49 = private unnamed_addr constant [75 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_enum_simple.out\00", align 1
@str.50 = private unnamed_addr constant [75 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_enum_verify.out\00", align 1
@str.51 = private unnamed_addr constant [68 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_enum.out\00", align 1
@str.52 = private unnamed_addr constant [73 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_ext_parse.out\00", align 1
@str.53 = private unnamed_addr constant [74 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_ext_simple.out\00", align 1
@str.54 = private unnamed_addr constant [82 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_extension_complete.out\00", align 1
@str.55 = private unnamed_addr constant [79 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_extension_final.out\00", align 1
@str.56 = private unnamed_addr constant [80 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_extension_method.out\00", align 1
@str.57 = private unnamed_addr constant [81 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_extension_method2.out\00", align 1
@str.58 = private unnamed_addr constant [73 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_extension.out\00", align 1
@str.59 = private unnamed_addr constant [77 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_extern_printf.out\00", align 1
@str.60 = private unnamed_addr constant [70 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_extern.out\00", align 1
@str.61 = private unnamed_addr constant [72 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_features.out\00", align 1
@str.62 = private unnamed_addr constant [74 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_ffi_simple.out\00", align 1
@str.63 = private unnamed_addr constant [71 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_file_io.out\00", align 1
@str.64 = private unnamed_addr constant [80 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_final_validation.out\00", align 1
@str.65 = private unnamed_addr constant [69 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_float.out\00", align 1
@str.66 = private unnamed_addr constant [71 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_for_mut.out\00", align 1
@str.67 = private unnamed_addr constant [67 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_for.out\00", align 1
@str.68 = private unnamed_addr constant [72 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_fs_basic.out\00", align 1
@str.69 = private unnamed_addr constant [72 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_generics.out\00", align 1
@str.70 = private unnamed_addr constant [80 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_hashmap_indexing.out\00", align 1
@str.71 = private unnamed_addr constant [71 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_hashmap.out\00", align 1
@str.72 = private unnamed_addr constant [71 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_hashset.out\00", align 1
@str.73 = private unnamed_addr constant [66 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_if.out\00", align 1
@str.74 = private unnamed_addr constant [73 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_impl_show.out\00", align 1
@str.75 = private unnamed_addr constant [75 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_impl_simple.out\00", align 1
@str.76 = private unnamed_addr constant [68 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_impl.out\00", align 1
@str.77 = private unnamed_addr constant [68 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_json.out\00", align 1
@str.78 = private unnamed_addr constant [77 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_lambda_simple.out\00", align 1
@str.79 = private unnamed_addr constant [71 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_len_bug.out\00", align 1
@str.80 = private unnamed_addr constant [67 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_len.out\00", align 1
@str.81 = private unnamed_addr constant [71 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_logical.out\00", align 1
@str.82 = private unnamed_addr constant [69 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_macro.out\00", align 1
@str.83 = private unnamed_addr constant [75 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_match_debug.out\00", align 1
@str.84 = private unnamed_addr constant [75 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_match_small.out\00", align 1
@str.85 = private unnamed_addr constant [74 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_match_stmt.out\00", align 1
@str.86 = private unnamed_addr constant [69 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_match.out\00", align 1
@str.87 = private unnamed_addr constant [77 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_math_advanced.out\00", align 1
@str.88 = private unnamed_addr constant [76 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_math_various.out\00", align 1
@str.89 = private unnamed_addr constant [71 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_modules.out\00", align 1
@str.90 = private unnamed_addr constant [85 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_multiple_method_calls.out\00", align 1
@str.91 = private unnamed_addr constant [73 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_mut_debug.out\00", align 1
@str.92 = private unnamed_addr constant [74 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_mut_simple.out\00", align 1
@str.93 = private unnamed_addr constant [67 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_mut.out\00", align 1
@str.94 = private unnamed_addr constant [76 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_new_features.out\00", align 1
@str.95 = private unnamed_addr constant [75 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_new_methods.out\00", align 1
@str.96 = private unnamed_addr constant [78 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_number_methods.out\00", align 1
@str.97 = private unnamed_addr constant [75 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_oop_methods.out\00", align 1
@str.98 = private unnamed_addr constant [85 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_option_result_methods.out\00", align 1
@str.99 = private unnamed_addr constant [75 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_option_type.out\00", align 1
@str.100 = private unnamed_addr constant [78 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_optional_basic.out\00", align 1
@str.101 = private unnamed_addr constant [80 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_optional_bracket.out\00", align 1
@str.102 = private unnamed_addr constant [78 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_optional_match.out\00", align 1
@str.103 = private unnamed_addr constant [77 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_optional_none.out\00", align 1
@str.104 = private unnamed_addr constant [79 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_optional_simple.out\00", align 1
@str.105 = private unnamed_addr constant [77 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_optional_type.out\00", align 1
@str.106 = private unnamed_addr constant [72 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_optional.out\00", align 1
@str.107 = private unnamed_addr constant [74 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_print_bool.out\00", align 1
@str.108 = private unnamed_addr constant [81 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_print_polymorphic.out\00", align 1
@str.109 = private unnamed_addr constant [69 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_print.out\00", align 1
@str.110 = private unnamed_addr constant [77 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_question_mark.out\00", align 1
@str.111 = private unnamed_addr constant [77 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_result_simple.out\00", align 1
@str.112 = private unnamed_addr constant [70 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_result.out\00", align 1
@str.113 = private unnamed_addr constant [76 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_simple_match.out\00", align 1
@str.114 = private unnamed_addr constant [75 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_spawn_basic.out\00", align 1
@str.115 = private unnamed_addr constant [74 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_spawn_many.out\00", align 1
@str.116 = private unnamed_addr constant [78 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_spawn_multiple.out\00", align 1
@str.117 = private unnamed_addr constant [78 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_spawn_parallel.out\00", align 1
@str.118 = private unnamed_addr constant [83 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_spawn_same_multiple.out\00", align 1
@str.119 = private unnamed_addr constant [79 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_spawn_threading.out\00", align 1
@str.120 = private unnamed_addr constant [80 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_starts_ends_with.out\00", align 1
@str.121 = private unnamed_addr constant [84 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_stdlib_comprehensive.out\00", align 1
@str.122 = private unnamed_addr constant [77 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_stdlib_crypto.out\00", align 1
@str.123 = private unnamed_addr constant [75 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_stdlib_math.out\00", align 1
@str.124 = private unnamed_addr constant [75 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_stdlib_real.out\00", align 1
@str.125 = private unnamed_addr constant [75 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_stdlib_time.out\00", align 1
@str.126 = private unnamed_addr constant [74 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_str_concat.out\00", align 1
@str.127 = private unnamed_addr constant [77 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_string_concat.out\00", align 1
@str.128 = private unnamed_addr constant [76 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_string_final.out\00", align 1
@str.129 = private unnamed_addr constant [78 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_string_methods.out\00", align 1
@str.130 = private unnamed_addr constant [74 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_string_ops.out\00", align 1
@str.131 = private unnamed_addr constant [81 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_string_trim_split.out\00", align 1
@str.132 = private unnamed_addr constant [70 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_string.out\00", align 1
@str.133 = private unnamed_addr constant [71 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_strings.out\00", align 1
@str.134 = private unnamed_addr constant [83 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_struct_field_assign.out\00", align 1
@str.135 = private unnamed_addr constant [71 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_structs.out\00", align 1
@str.136 = private unnamed_addr constant [75 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_thread_pool.out\00", align 1
@str.137 = private unnamed_addr constant [82 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_time_comprehensive.out\00", align 1
@str.138 = private unnamed_addr constant [72 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_time_now.out\00", align 1
@str.139 = private unnamed_addr constant [76 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_time_scaling.out\00", align 1
@str.140 = private unnamed_addr constant [75 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_time_simple.out\00", align 1
@str.141 = private unnamed_addr constant [73 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_to_string.out\00", align 1
@str.142 = private unnamed_addr constant [74 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_trait_impl.out\00", align 1
@str.143 = private unnamed_addr constant [76 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_traits_final.out\00", align 1
@str.144 = private unnamed_addr constant [76 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_traits_multi.out\00", align 1
@str.145 = private unnamed_addr constant [79 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_traits_noparams.out\00", align 1
@str.146 = private unnamed_addr constant [75 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_traits_self.out\00", align 1
@str.147 = private unnamed_addr constant [77 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_traits_simple.out\00", align 1
@str.148 = private unnamed_addr constant [76 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_traits_typed.out\00", align 1
@str.149 = private unnamed_addr constant [70 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_traits.out\00", align 1
@str.150 = private unnamed_addr constant [69 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_tuple.out\00", align 1
@str.151 = private unnamed_addr constant [73 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_two_calls.out\00", align 1
@str.152 = private unnamed_addr constant [79 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_type_alias_full.out\00", align 1
@str.153 = private unnamed_addr constant [81 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_type_alias_simple.out\00", align 1
@str.154 = private unnamed_addr constant [74 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_type_alias.out\00", align 1
@str.155 = private unnamed_addr constant [76 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_type_aliases.out\00", align 1
@str.156 = private unnamed_addr constant [73 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_type_anno.out\00", align 1
@str.157 = private unnamed_addr constant [83 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_type_aware_dispatch.out\00", align 1
@str.158 = private unnamed_addr constant [78 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_type_inference.out\00", align 1
@str.159 = private unnamed_addr constant [74 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_typeof_bug.out\00", align 1
@str.160 = private unnamed_addr constant [70 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_typeof.out\00", align 1
@str.161 = private unnamed_addr constant [70 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_unsafe.out\00", align 1
@str.162 = private unnamed_addr constant [75 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_upper_lower.out\00", align 1
@str.163 = private unnamed_addr constant [73 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_utilities.out\00", align 1
@str.164 = private unnamed_addr constant [74 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_validation.out\00", align 1
@str.165 = private unnamed_addr constant [69 x i8] c"timeout 2 /Users/aoaws/src/ao/wyn-lang/wyn/tests/unit/test_while.out\00", align 1

declare ptr @malloc(i64)

declare void @free(ptr)

declare i32 @printf(ptr, ...)

define i32 @wyn_main() {
entry:
  %failures = alloca i32, align 4
  %pool_add = call i32 @pool_add_task(ptr @str)
  %pool_add1 = call i32 @pool_add_task(ptr @str.1)
  %pool_add2 = call i32 @pool_add_task(ptr @str.2)
  %pool_add3 = call i32 @pool_add_task(ptr @str.3)
  %pool_add4 = call i32 @pool_add_task(ptr @str.4)
  %pool_add5 = call i32 @pool_add_task(ptr @str.5)
  %pool_add6 = call i32 @pool_add_task(ptr @str.6)
  %pool_add7 = call i32 @pool_add_task(ptr @str.7)
  %pool_add8 = call i32 @pool_add_task(ptr @str.8)
  %pool_add9 = call i32 @pool_add_task(ptr @str.9)
  %pool_add10 = call i32 @pool_add_task(ptr @str.10)
  %pool_add11 = call i32 @pool_add_task(ptr @str.11)
  %pool_add12 = call i32 @pool_add_task(ptr @str.12)
  %pool_add13 = call i32 @pool_add_task(ptr @str.13)
  %pool_add14 = call i32 @pool_add_task(ptr @str.14)
  %pool_add15 = call i32 @pool_add_task(ptr @str.15)
  %pool_add16 = call i32 @pool_add_task(ptr @str.16)
  %pool_add17 = call i32 @pool_add_task(ptr @str.17)
  %pool_add18 = call i32 @pool_add_task(ptr @str.18)
  %pool_add19 = call i32 @pool_add_task(ptr @str.19)
  %pool_add20 = call i32 @pool_add_task(ptr @str.20)
  %pool_add21 = call i32 @pool_add_task(ptr @str.21)
  %pool_add22 = call i32 @pool_add_task(ptr @str.22)
  %pool_add23 = call i32 @pool_add_task(ptr @str.23)
  %pool_add24 = call i32 @pool_add_task(ptr @str.24)
  %pool_add25 = call i32 @pool_add_task(ptr @str.25)
  %pool_add26 = call i32 @pool_add_task(ptr @str.26)
  %pool_add27 = call i32 @pool_add_task(ptr @str.27)
  %pool_add28 = call i32 @pool_add_task(ptr @str.28)
  %pool_add29 = call i32 @pool_add_task(ptr @str.29)
  %pool_add30 = call i32 @pool_add_task(ptr @str.30)
  %pool_add31 = call i32 @pool_add_task(ptr @str.31)
  %pool_add32 = call i32 @pool_add_task(ptr @str.32)
  %pool_add33 = call i32 @pool_add_task(ptr @str.33)
  %pool_add34 = call i32 @pool_add_task(ptr @str.34)
  %pool_add35 = call i32 @pool_add_task(ptr @str.35)
  %pool_add36 = call i32 @pool_add_task(ptr @str.36)
  %pool_add37 = call i32 @pool_add_task(ptr @str.37)
  %pool_add38 = call i32 @pool_add_task(ptr @str.38)
  %pool_add39 = call i32 @pool_add_task(ptr @str.39)
  %pool_add40 = call i32 @pool_add_task(ptr @str.40)
  %pool_add41 = call i32 @pool_add_task(ptr @str.41)
  %pool_add42 = call i32 @pool_add_task(ptr @str.42)
  %pool_add43 = call i32 @pool_add_task(ptr @str.43)
  %pool_add44 = call i32 @pool_add_task(ptr @str.44)
  %pool_add45 = call i32 @pool_add_task(ptr @str.45)
  %pool_add46 = call i32 @pool_add_task(ptr @str.46)
  %pool_add47 = call i32 @pool_add_task(ptr @str.47)
  %pool_add48 = call i32 @pool_add_task(ptr @str.48)
  %pool_add49 = call i32 @pool_add_task(ptr @str.49)
  %pool_add50 = call i32 @pool_add_task(ptr @str.50)
  %pool_add51 = call i32 @pool_add_task(ptr @str.51)
  %pool_add52 = call i32 @pool_add_task(ptr @str.52)
  %pool_add53 = call i32 @pool_add_task(ptr @str.53)
  %pool_add54 = call i32 @pool_add_task(ptr @str.54)
  %pool_add55 = call i32 @pool_add_task(ptr @str.55)
  %pool_add56 = call i32 @pool_add_task(ptr @str.56)
  %pool_add57 = call i32 @pool_add_task(ptr @str.57)
  %pool_add58 = call i32 @pool_add_task(ptr @str.58)
  %pool_add59 = call i32 @pool_add_task(ptr @str.59)
  %pool_add60 = call i32 @pool_add_task(ptr @str.60)
  %pool_add61 = call i32 @pool_add_task(ptr @str.61)
  %pool_add62 = call i32 @pool_add_task(ptr @str.62)
  %pool_add63 = call i32 @pool_add_task(ptr @str.63)
  %pool_add64 = call i32 @pool_add_task(ptr @str.64)
  %pool_add65 = call i32 @pool_add_task(ptr @str.65)
  %pool_add66 = call i32 @pool_add_task(ptr @str.66)
  %pool_add67 = call i32 @pool_add_task(ptr @str.67)
  %pool_add68 = call i32 @pool_add_task(ptr @str.68)
  %pool_add69 = call i32 @pool_add_task(ptr @str.69)
  %pool_add70 = call i32 @pool_add_task(ptr @str.70)
  %pool_add71 = call i32 @pool_add_task(ptr @str.71)
  %pool_add72 = call i32 @pool_add_task(ptr @str.72)
  %pool_add73 = call i32 @pool_add_task(ptr @str.73)
  %pool_add74 = call i32 @pool_add_task(ptr @str.74)
  %pool_add75 = call i32 @pool_add_task(ptr @str.75)
  %pool_add76 = call i32 @pool_add_task(ptr @str.76)
  %pool_add77 = call i32 @pool_add_task(ptr @str.77)
  %pool_add78 = call i32 @pool_add_task(ptr @str.78)
  %pool_add79 = call i32 @pool_add_task(ptr @str.79)
  %pool_add80 = call i32 @pool_add_task(ptr @str.80)
  %pool_add81 = call i32 @pool_add_task(ptr @str.81)
  %pool_add82 = call i32 @pool_add_task(ptr @str.82)
  %pool_add83 = call i32 @pool_add_task(ptr @str.83)
  %pool_add84 = call i32 @pool_add_task(ptr @str.84)
  %pool_add85 = call i32 @pool_add_task(ptr @str.85)
  %pool_add86 = call i32 @pool_add_task(ptr @str.86)
  %pool_add87 = call i32 @pool_add_task(ptr @str.87)
  %pool_add88 = call i32 @pool_add_task(ptr @str.88)
  %pool_add89 = call i32 @pool_add_task(ptr @str.89)
  %pool_add90 = call i32 @pool_add_task(ptr @str.90)
  %pool_add91 = call i32 @pool_add_task(ptr @str.91)
  %pool_add92 = call i32 @pool_add_task(ptr @str.92)
  %pool_add93 = call i32 @pool_add_task(ptr @str.93)
  %pool_add94 = call i32 @pool_add_task(ptr @str.94)
  %pool_add95 = call i32 @pool_add_task(ptr @str.95)
  %pool_add96 = call i32 @pool_add_task(ptr @str.96)
  %pool_add97 = call i32 @pool_add_task(ptr @str.97)
  %pool_add98 = call i32 @pool_add_task(ptr @str.98)
  %pool_add99 = call i32 @pool_add_task(ptr @str.99)
  %pool_add100 = call i32 @pool_add_task(ptr @str.100)
  %pool_add101 = call i32 @pool_add_task(ptr @str.101)
  %pool_add102 = call i32 @pool_add_task(ptr @str.102)
  %pool_add103 = call i32 @pool_add_task(ptr @str.103)
  %pool_add104 = call i32 @pool_add_task(ptr @str.104)
  %pool_add105 = call i32 @pool_add_task(ptr @str.105)
  %pool_add106 = call i32 @pool_add_task(ptr @str.106)
  %pool_add107 = call i32 @pool_add_task(ptr @str.107)
  %pool_add108 = call i32 @pool_add_task(ptr @str.108)
  %pool_add109 = call i32 @pool_add_task(ptr @str.109)
  %pool_add110 = call i32 @pool_add_task(ptr @str.110)
  %pool_add111 = call i32 @pool_add_task(ptr @str.111)
  %pool_add112 = call i32 @pool_add_task(ptr @str.112)
  %pool_add113 = call i32 @pool_add_task(ptr @str.113)
  %pool_add114 = call i32 @pool_add_task(ptr @str.114)
  %pool_add115 = call i32 @pool_add_task(ptr @str.115)
  %pool_add116 = call i32 @pool_add_task(ptr @str.116)
  %pool_add117 = call i32 @pool_add_task(ptr @str.117)
  %pool_add118 = call i32 @pool_add_task(ptr @str.118)
  %pool_add119 = call i32 @pool_add_task(ptr @str.119)
  %pool_add120 = call i32 @pool_add_task(ptr @str.120)
  %pool_add121 = call i32 @pool_add_task(ptr @str.121)
  %pool_add122 = call i32 @pool_add_task(ptr @str.122)
  %pool_add123 = call i32 @pool_add_task(ptr @str.123)
  %pool_add124 = call i32 @pool_add_task(ptr @str.124)
  %pool_add125 = call i32 @pool_add_task(ptr @str.125)
  %pool_add126 = call i32 @pool_add_task(ptr @str.126)
  %pool_add127 = call i32 @pool_add_task(ptr @str.127)
  %pool_add128 = call i32 @pool_add_task(ptr @str.128)
  %pool_add129 = call i32 @pool_add_task(ptr @str.129)
  %pool_add130 = call i32 @pool_add_task(ptr @str.130)
  %pool_add131 = call i32 @pool_add_task(ptr @str.131)
  %pool_add132 = call i32 @pool_add_task(ptr @str.132)
  %pool_add133 = call i32 @pool_add_task(ptr @str.133)
  %pool_add134 = call i32 @pool_add_task(ptr @str.134)
  %pool_add135 = call i32 @pool_add_task(ptr @str.135)
  %pool_add136 = call i32 @pool_add_task(ptr @str.136)
  %pool_add137 = call i32 @pool_add_task(ptr @str.137)
  %pool_add138 = call i32 @pool_add_task(ptr @str.138)
  %pool_add139 = call i32 @pool_add_task(ptr @str.139)
  %pool_add140 = call i32 @pool_add_task(ptr @str.140)
  %pool_add141 = call i32 @pool_add_task(ptr @str.141)
  %pool_add142 = call i32 @pool_add_task(ptr @str.142)
  %pool_add143 = call i32 @pool_add_task(ptr @str.143)
  %pool_add144 = call i32 @pool_add_task(ptr @str.144)
  %pool_add145 = call i32 @pool_add_task(ptr @str.145)
  %pool_add146 = call i32 @pool_add_task(ptr @str.146)
  %pool_add147 = call i32 @pool_add_task(ptr @str.147)
  %pool_add148 = call i32 @pool_add_task(ptr @str.148)
  %pool_add149 = call i32 @pool_add_task(ptr @str.149)
  %pool_add150 = call i32 @pool_add_task(ptr @str.150)
  %pool_add151 = call i32 @pool_add_task(ptr @str.151)
  %pool_add152 = call i32 @pool_add_task(ptr @str.152)
  %pool_add153 = call i32 @pool_add_task(ptr @str.153)
  %pool_add154 = call i32 @pool_add_task(ptr @str.154)
  %pool_add155 = call i32 @pool_add_task(ptr @str.155)
  %pool_add156 = call i32 @pool_add_task(ptr @str.156)
  %pool_add157 = call i32 @pool_add_task(ptr @str.157)
  %pool_add158 = call i32 @pool_add_task(ptr @str.158)
  %pool_add159 = call i32 @pool_add_task(ptr @str.159)
  %pool_add160 = call i32 @pool_add_task(ptr @str.160)
  %pool_add161 = call i32 @pool_add_task(ptr @str.161)
  %pool_add162 = call i32 @pool_add_task(ptr @str.162)
  %pool_add163 = call i32 @pool_add_task(ptr @str.163)
  %pool_add164 = call i32 @pool_add_task(ptr @str.164)
  %pool_add165 = call i32 @pool_add_task(ptr @str.165)
  %pool_start = call void @pool_start(i32 50)
  %pool_wait = call i32 @pool_wait()
  store i32 %pool_wait, ptr %failures, align 4
  %failures166 = load i32, ptr %failures, align 4
  ret i32 %failures166
}

declare i32 @pool_add_task(ptr)

declare void @pool_start(i32)

declare i32 @pool_wait()
