#ifndef WYN_COMMON_H
#define WYN_COMMON_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef enum {
    TOKEN_EOF,
    TOKEN_INT, TOKEN_FLOAT, TOKEN_STRING, TOKEN_CHAR, TOKEN_IDENT,
    TOKEN_FN, TOKEN_STRUCT, TOKEN_ENUM, TOKEN_TYPE, TOKEN_IMPL, TOKEN_TRAIT, TOKEN_MAP, TOKEN_EXTERN, TOKEN_UNSAFE, TOKEN_MACRO,
    TOKEN_VAR, TOKEN_CONST, TOKEN_MUT, TOKEN_PUB, TOKEN_LET,
    TOKEN_IF, TOKEN_ELSE, TOKEN_ELSEIF, TOKEN_MATCH, TOKEN_FOR, TOKEN_WHILE, TOKEN_IN,
    TOKEN_BREAK, TOKEN_CONTINUE, TOKEN_RETURN,
    TOKEN_TRY, TOKEN_CATCH, TOKEN_FINALLY, TOKEN_THROW,
    TOKEN_IMPORT, TOKEN_FROM, TOKEN_AS, TOKEN_EXPORT, TOKEN_MODULE,
    TOKEN_TRUE, TOKEN_FALSE, TOKEN_NULL,
    TOKEN_TEST, TOKEN_ASSERT,
    TOKEN_SOME, TOKEN_NONE, TOKEN_OK, TOKEN_ERR,
    TOKEN_SPAWN, TOKEN_CHANNEL, TOKEN_ASYNC, TOKEN_AWAIT,
    TOKEN_AND, TOKEN_OR, TOKEN_NOT,
    TOKEN_AMPAMP, TOKEN_PIPEPIPE,
    TOKEN_PLUS, TOKEN_MINUS, TOKEN_STAR, TOKEN_SLASH, TOKEN_PERCENT,
    TOKEN_AMP, TOKEN_PIPE, TOKEN_CARET, TOKEN_TILDE, TOKEN_LSHIFT, TOKEN_RSHIFT,
    TOKEN_EQ, TOKEN_EQEQ, TOKEN_BANG, TOKEN_BANGEQ,
    TOKEN_PLUSPLUS, TOKEN_MINUSMINUS,
    TOKEN_PLUSEQ, TOKEN_MINUSEQ, TOKEN_STAREQ, TOKEN_SLASHEQ,
    TOKEN_LT, TOKEN_GT, TOKEN_LTEQ, TOKEN_GTEQ,
    TOKEN_LPAREN, TOKEN_RPAREN, TOKEN_LBRACE, TOKEN_RBRACE, TOKEN_LBRACKET, TOKEN_RBRACKET,
    TOKEN_COMMA, TOKEN_COLON, TOKEN_COLONCOLON, TOKEN_SEMI, TOKEN_DOT, TOKEN_DOTDOT, TOKEN_DOTDOTDOT, TOKEN_ARROW, TOKEN_FATARROW, TOKEN_QUESTION, TOKEN_PIPEGT, TOKEN_PIPE_CLOSURE, TOKEN_QUESTION_DOT, TOKEN_UNDERSCORE,
} TokenType;

typedef struct {
    TokenType type;
    const char* start;
    int length;
    int line;
} Token;

#endif
