#ifndef WYN_OPTIONAL_H
#define WYN_OPTIONAL_H

#include <stdbool.h>
#include <stddef.h>

// Optional type representation
typedef struct {
    bool has_value;
    void* value;
    size_t value_size;
} WynOptional;

// Optional type constructors
WynOptional* wyn_some(void* value, size_t size);
WynOptional* wyn_none(void);

// Optional type operations
bool wyn_optional_is_some(WynOptional* opt);
bool wyn_optional_is_none(WynOptional* opt);
void* wyn_optional_unwrap(WynOptional* opt);
void* wyn_optional_unwrap_or(WynOptional* opt, void* default_value);

// Pattern matching support
bool wyn_optional_match_some(WynOptional* opt, void** out_value);
bool wyn_optional_match_none(WynOptional* opt);

// Memory management
void wyn_optional_free(WynOptional* opt);

// Type-specific constructors (generated by codegen)
WynOptional* some_int(int value);
WynOptional* some_float(float value);
WynOptional* some_string(const char* value);
WynOptional* some_bool(bool value);
WynOptional* none_int(void);
WynOptional* none_float(void);
WynOptional* none_string(void);
WynOptional* none_bool(void);

// Type-specific unwrappers
int unwrap_int(WynOptional* opt);
float unwrap_float(WynOptional* opt);
const char* unwrap_string(WynOptional* opt);
bool unwrap_bool(WynOptional* opt);

// Additional function declarations
void* create_scope(void* parent_scope);

#endif